name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install black
        run: python3 -m pip install black

      - name: Check code formatting
        run: black . --check

  tests:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: python3 -m pip install -r requirements_test.txt

      - name: Run tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.kamstrup_403 \
            --cov-report=xml \
            -o console_output_style=count \
            -p no:sugar \
            tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: coverage-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
